server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:file:~/.h2/test
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
    username: sa
    password: sa
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    sql-script-encoding: utf-8
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  config: classpath:logback-spring.xml
